MVCFacturacion/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCFacturacion.Controllers
{
    public class PrincipalController : Controller
    {
        // GET: Principal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Ayuda()
        {
            return View();
        }

        public ActionResult Acerca()
        {
            return View();
        }

        public ActionResult Contacto()
        {
            return View();
        }
    }
}

MVCFacturacion/Controllers/TBLEmpleadoController.cs
using MVCFacturacion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCFacturacion.Controllers
{
    public class TBLEmpleadoController : Controller
    {
        // GET: TBLEmpleado
        public ActionResult Index()
        {
            DBFacturacion db = new DBFacturacion();
            var empleados = db.TBLEMPLEADO;
            return View(empleados.ToList());
        }

        public ActionResult Nuevo()
        {
            DBFacturacion db = new DBFacturacion();
            ViewBag.IdRolEmpleado = new SelectList(db.TBLROLES, "IdRolEmpleado", "StrDescripcion");
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DBFacturacion db = new DBFacturacion();
                    var NuevoDatos = new TBLEMPLEADO();
                    NuevoDatos.strNombre = collection["strNombre"];
                    NuevoDatos.NumDocumento = long.Parse(collection["NumDocumento"]);
                    NuevoDatos.StrDireccion = collection["StrDireccion"];
                    NuevoDatos.StrTelefono = collection["StrTelefono"];
                    NuevoDatos.StrEmail = collection["StrEmail"];
                    NuevoDatos.IdRolEmpleado = int.Parse(collection["IdRolEmpleado"]);
                    NuevoDatos.DtmIngreso = Convert.ToDateTime(collection["DtmIngreso"]);
                    NuevoDatos.DtmRetiro = Convert.ToDateTime(collection["DtmRetiro"]);
                    NuevoDatos.strDatosAdicionales = collection["strDatosAdicionales"];
                    NuevoDatos.DtmFechaModifica = DateTime.Now.Date;
                    NuevoDatos.StrUsuarioModifico = "javier";
                    db.TBLEMPLEADO.Add(NuevoDatos);
                    db.SaveChanges();
                    return Redirect("/TBLEmpleado/index");
                }
                return View(collection);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        public ActionResult Editar(int id)
        {
            DBFacturacion db = new DBFacturacion();
            var DatosEmple = db.TBLEMPLEADO.Find(id);
            DBFacturacion db2 = new DBFacturacion();
            ViewBag.IdRolEmpleado = new SelectList(db2.TBLROLES, "IdRolEmpleado", "StrDescripcion",
           DatosEmple.IdRolEmpleado);
            return View(DatosEmple);
        }
        [HttpPost]
        public ActionResult Editar(TBLEMPLEADO model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBFacturacion db = new DBFacturacion())
                    {
                        var DatosModifi = db.TBLEMPLEADO.Find(model.IdEmpleado);
                        DatosModifi.strNombre = model.strNombre;
                        DatosModifi.NumDocumento = model.NumDocumento;
                        DatosModifi.StrDireccion = model.StrDireccion;
                        DatosModifi.StrTelefono = model.StrTelefono;
                        DatosModifi.StrEmail = model.StrEmail;
                        DatosModifi.IdRolEmpleado = model.IdRolEmpleado;
                        DatosModifi.DtmIngreso = model.DtmIngreso;
                        DatosModifi.DtmRetiro = model.DtmRetiro;
                        DatosModifi.strDatosAdicionales = model.strDatosAdicionales;
                        DatosModifi.DtmFechaModifica = DateTime.Now.Date;
                        DatosModifi.StrUsuarioModifico = "javier";
                        db.Entry(DatosModifi).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("/TBLEmpleado/index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        [HttpGet]
        public ActionResult Borrar(int id)
        {
            try
            {
                using (DBFacturacion db = new DBFacturacion())
                {
                    var otabla = db.TBLEMPLEADO.Find(id);
                    db.TBLEMPLEADO.Remove(otabla);
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return Redirect("/TBLEmpleado/index");
        }
    }

}

MVCFacturacion/Controllers/TBLProductosController.cs
using MVCFacturacion.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MVCFacturacion.Controllers
{
    public class TBLProductosController : Controller
    {
        // GET: TBLProductos
        public ActionResult Index()
        {
            using (var db = new DBFacturacion())
            {
                var productos = db.TBLPRODUCTO
                         .Include(p => p.TBLCATEGORIA_PROD) 
                         .ToList();
                return View(productos);
            }
        }
        public ActionResult Nuevo()
        {
            using (var db = new DBFacturacion())
            {
                ViewBag.IdCategoria = new SelectList(db.TBLCATEGORIA_PROD.ToList(), "IdCategoria", "StrDescripcion");
                return View();
            }
        }

        [HttpPost]
        public ActionResult Nuevo(TBLPRODUCTO model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var db = new DBFacturacion())
                    {
                        model.DtmFechaModifica = DateTime.Now;
                        model.StrUsuarioModifica = "javier";
                        db.TBLPRODUCTO.Add(model);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }

                using (var db = new DBFacturacion())
                {
                    ViewBag.IdCategoria = new SelectList(db.TBLCATEGORIA_PROD.ToList(), "IdCategoria", "StrDescripcion");
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            using (var db = new DBFacturacion())
            {
                var producto = db.TBLPRODUCTO.Find(id);
                ViewBag.IdCategoria = new SelectList(db.TBLCATEGORIA_PROD.ToList(), "IdCategoria", "StrDescripcion");
                return View(producto);
            }
        }

        [HttpPost]
        public ActionResult Editar(TBLPRODUCTO model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var db = new DBFacturacion())
                    {
                        var producto = db.TBLPRODUCTO.Find(model.IdProducto);
                        producto.StrNombre = model.StrNombre;
                        producto.StrCodigo = model.StrCodigo;
                        producto.NumPrecioCompra = model.NumPrecioCompra;
                        producto.NumPrecioVenta = model.NumPrecioVenta;
                        producto.IdCategoria = model.IdCategoria;
                        producto.StrDetalle = model.StrDetalle;
                        producto.strFoto = model.strFoto;
                        producto.NumStock = model.NumStock;
                        producto.DtmFechaModifica = DateTime.Now;
                        producto.StrUsuarioModifica = "javier";

                        db.Entry(producto).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }

                using (var db = new DBFacturacion())
                {
                    ViewBag.IdCategoria = new SelectList(db.TBLCATEGORIA_PROD.ToList(), "IdCategoria", "StrNombre", model.IdCategoria);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Borrar(int id)
        {
            try
            {
                using (var db = new DBFacturacion())
                {
                    var producto = db.TBLPRODUCTO.Find(id);
                    db.TBLPRODUCTO.Remove(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

MVCFacturacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Principal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "Acerca", "Principal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contacto", "Principal", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Ayuda", "Ayuda", "Principal", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCFacturacion/Views/Shared/_LayoutFacturacion.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 565px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #483D8B;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @@media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">FACTURACIÓN</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Inicio", "Index", "Principal")</li>
                    <li>@Html.ActionLink("Acerca", "Acerca", "Principal")</li>
                    <li>@Html.ActionLink("Ayuda", "Ayuda", "Principal")</li>
                    <li>@Html.ActionLink("Contacto", "Contacto", "Principal")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid text-center">
        <div class="row content">
            <div class="col-sm-2 sidenav">



                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse1">TABLAS</a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="panel-body">@Html.ActionLink("Clientes", "Index", "TBLClientes")</div>
                            <div class="panel-body">@Html.ActionLink("Productos", "Index", "TBLProductos")</div>
                            <div class="panel-body">Categorias</div>
                        </div>
                    </div>
                </div>


                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse2">FACTURAS</a>
                            </h4>
                        </div>
                        <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body">Facturas</div>
                            <div class="panel-body">Informes</div>
                        </div>
                    </div>
                </div>


                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse3">SEGURIDAD</a>
                            </h4>
                        </div>
                        <div id="collapse3" class="panel-collapse collapse">
                            <div class="panel-body">@Html.ActionLink("Empleados", "Index", "TBLEmpleado")</div>
                            <div class="panel-body">Roles</div>
                            <div class="panel-body">Seguridad</div>
                        </div>
                    </div>
                </div>


            </div>
            <div class="col-sm-10 text-left">
                @RenderBody();


            </div>
        </div>
    </div>

    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>

</body>
</html>